mysql --host=localhost --user=bid4win --password=bid4win bid4win_db_test < ../BID4WIN_DB.BID4WIN/DOWNGRADE_2_V_0_0_0/TABLE_PROPERTY.SQL
mysql --host=localhost --user=bid4win --password=bid4win bid4win_db_test < ../BID4WIN_DB.BID4WIN/DOWNGRADE_2_V_0_0_0/TABLE_PROPERTY_ROOT.SQL

mysql --host=localhost --user=bid4win --password=bid4win bid4win_db_test < ../BID4WIN_DB.BID4WIN/DOWNGRADE_2_V_0_0_0/TABLE_CONNECTION.SQL
mysql --host=localhost --user=bid4win --password=bid4win bid4win_db_test < ../BID4WIN_DB.BID4WIN/DOWNGRADE_2_V_0_0_0/TABLE_CONNECTION_HISTORY.SQL
mysql --host=localhost --user=bid4win --password=bid4win bid4win_db_test < ../BID4WIN_DB.BID4WIN/DOWNGRADE_2_V_0_0_0/TABLE_PASSWORD_REINIT.SQL
mysql --host=localhost --user=bid4win --password=bid4win bid4win_db_test < ../BID4WIN_DB.BID4WIN/DOWNGRADE_2_V_0_0_0/TABLE_SUBSCRIPTION.SQL

mysql --host=localhost --user=bid4win --password=bid4win bid4win_db_test < ../BID4WIN_DB.BID4WIN/DOWNGRADE_2_V_0_0_0/TABLE_NORMAL_USAGE.SQL
mysql --host=localhost --user=bid4win --password=bid4win bid4win_db_test < ../BID4WIN_DB.BID4WIN/DOWNGRADE_2_V_0_0_0/TABLE_NORMAL_USAGE_HISTORY.SQL
mysql --host=localhost --user=bid4win --password=bid4win bid4win_db_test < ../BID4WIN_DB.BID4WIN/DOWNGRADE_2_V_0_0_0/TABLE_NORMAL_INVOLVEMENT.SQL
mysql --host=localhost --user=bid4win --password=bid4win bid4win_db_test < ../BID4WIN_DB.BID4WIN/DOWNGRADE_2_V_0_0_0/TABLE_NORMAL_INVOLVEMENT_HISTORY.SQL
mysql --host=localhost --user=bid4win --password=bid4win bid4win_db_test < ../BID4WIN_DB.BID4WIN/DOWNGRADE_2_V_0_0_0/TABLE_NORMAL_BOT.SQL
mysql --host=localhost --user=bid4win --password=bid4win bid4win_db_test < ../BID4WIN_DB.BID4WIN/DOWNGRADE_2_V_0_0_0/TABLE_NORMAL_BID.SQL
mysql --host=localhost --user=bid4win --password=bid4win bid4win_db_test < ../BID4WIN_DB.BID4WIN/DOWNGRADE_2_V_0_0_0/TABLE_NORMAL_BID_HISTORY.SQL
mysql --host=localhost --user=bid4win --password=bid4win bid4win_db_test < ../BID4WIN_DB.BID4WIN/DOWNGRADE_2_V_0_0_0/TABLE_NORMAL_AUCTION.SQL

mysql --host=localhost --user=bid4win --password=bid4win bid4win_db_test < ../BID4WIN_DB.BID4WIN/DOWNGRADE_2_V_0_0_0/TABLE_PREBOOKED_BID.SQL
mysql --host=localhost --user=bid4win --password=bid4win bid4win_db_test < ../BID4WIN_DB.BID4WIN/DOWNGRADE_2_V_0_0_0/TABLE_PREBOOKED_BID_HISTORY.SQL
mysql --host=localhost --user=bid4win --password=bid4win bid4win_db_test < ../BID4WIN_DB.BID4WIN/DOWNGRADE_2_V_0_0_0/TABLE_PREBOOKED_AUCTION.SQL

mysql --host=localhost --user=bid4win --password=bid4win bid4win_db_test < ../BID4WIN_DB.BID4WIN/DOWNGRADE_2_V_0_0_0/TABLE_IMAGE_USAGE.SQL
mysql --host=localhost --user=bid4win --password=bid4win bid4win_db_test < ../BID4WIN_DB.BID4WIN/DOWNGRADE_2_V_0_0_0/TABLE_IMAGE_STORAGE.SQL
mysql --host=localhost --user=bid4win --password=bid4win bid4win_db_test < ../BID4WIN_DB.BID4WIN/DOWNGRADE_2_V_0_0_0/TABLE_INNER_CONTENT_USAGE.SQL
mysql --host=localhost --user=bid4win --password=bid4win bid4win_db_test < ../BID4WIN_DB.BID4WIN/DOWNGRADE_2_V_0_0_0/TABLE_INNER_CONTENT_STORAGE.SQL

mysql --host=localhost --user=bid4win --password=bid4win bid4win_db_test < ../BID4WIN_DB.BID4WIN/DOWNGRADE_2_V_0_0_0/TABLE_PRODUCT.SQL

mysql --host=localhost --user=bid4win --password=bid4win bid4win_db_test < ../BID4WIN_DB.BID4WIN/DOWNGRADE_2_V_0_0_0/TABLE_CREDIT_BUNDLE.SQL
mysql --host=localhost --user=bid4win --password=bid4win bid4win_db_test < ../BID4WIN_DB.BID4WIN/DOWNGRADE_2_V_0_0_0/TABLE_CREDIT_BUNDLE_HISTORY.SQL
mysql --host=localhost --user=bid4win --password=bid4win bid4win_db_test < ../BID4WIN_DB.BID4WIN/DOWNGRADE_2_V_0_0_0/TABLE_ACCOUNT.SQL
